### ISSUE TITLE
glyph_map.size() = 0

### ISSUE THREAD

**Issue by Deins** [kv01/ttf-parser#1]
Hello! For some fonts glyph_map.size() == 0. Is it supposed to be so? How can I identify glyphs in those situations? Direct mapping like glyphs['A'] also doesn't work, and Glyph itself also doesn't store its codepoint, so i can't even manually search or identify them in any way.

Otherwise, seems like a good library ;)

**Comment by kv01** [comment]
glyph_map.size() will be 0 only if the cmap table of the font can't be parsed. In that case a conversion from character codes to glyph indices will not be possible. This should never happen though as all fonts should have a valid cmap table.
This parser however doesn't implement all possible formats of the cmap table yet so it might not read it from some fonts. I've loosened the checks a bit to allow for more fonts: [Platform check](https://github.com/kv01/ttf-parser/blob/01d1a8819f968b1e87264801e8f801810c5dce14/src/ttfParser.h#L536-L537) and [Format check](https://github.com/kv01/ttf-parser/blob/01d1a8819f968b1e87264801e8f801810c5dce14/src/ttfParser.h#L544-L545)
Let me know if it works with your font now. If not, a link to the font or the available platforms and formats in its cmap table will be helpful for me to add support for it.
Thanks!

**Comment by Deins** [comment]
yup, that fixed the problem, now glyph_map is full :+1: 
Thanks!

P.S. the font was just random test pick: http://www.1001freefonts.com/28_days_later.font
