### ISSUE TITLE
Can't get font name

### ISSUE THREAD

**Issue by jl-DaDar** [kv01/ttf-parser#2]
I tried to used this code to parse a font name,
but the resulting font name is garbage text. I used pretty much identical code in the example

**Comment by kv01** [comment]
Hello, is it just the font name that is garbage or even the glyph data?
Its been a while since I've looked at this but I'll be happy to investigate the problem if you can share the offending font.

**Comment by jl-DaDar** [comment]
I did not bother with glyph data as I only needed to find the font name.
it is a chinese font with an english name. 

https://jl-custom-stage-media-public.s3.ap-east-1.amazonaws.com/common/common_font_fonts/uwNMMQ8dRNC82EuxdfPIdQ/font_file_mediams_file_id-2Wxqr/zhankuwenyiti.ttf

**Comment by kv01** [comment]
I'm so sorry for not getting to this sooner. I've updated the code to handle font names better when there are multiple languages in the font and it should work for your font now. The example code was also changed to show how to get the font name now.
