### ISSUE TITLE
pseudo code for drawing a font

### ISSUE THREAD

**Issue by AlexVestin** [kv01/ttf-parser#3]
Thanks for open sourcing this! @kv01 
I'm having a bit of a problem understanding how to draw the parsed data.  Basically I have a path-renderer set up
and would like to do something like

```
for path in glyph.path_list:
  moveTo(path[0].point)
  for curve in path.curves[1:]:
     if curve.is_curve:
      quadTo (curve.points)
   else:
      lineTo(curve.points) 
```

What I don't grasp is what the point values in the triangle represent. 
> Quadratic splines will have 2 tiangles associated with them, (p_x, p1, p2) as before and (p1, p_c, p2) where p_c is the spline control point.

Are Quadratics split into two curve objects? And how would I use those in a path renderer?
What I've done right now is 
```c++
 for(int i = 0; i < rGlyph.path_list.size(); i++) {
        TTFFontParser::Path p = rGlyph.path_list[i];

        TTFFontParser::Curve c0 = p.curves[0];
        path.MoveTo(c0.p0.x, c0.p0.y);

        bool is_curve = false;
        for(int j = 1; j < p.curves.size(); j++) {
            TTFFontParser::Curve c = p.curves[j];
            if (c.is_curve) {
                is_curve = true;
                continue;
            }

            if (is_curve) {
                path.QuadTo(c.p2.x, c.p2.y, c.p1.x, c.p2.y);
            } else {
                path.LineTo(c.p2.x, c.p2.y);
            }
            is_curve = false;                
        }
    }
```

But produces some random lines. I realize this isn't a help hotline, but any pointers would be greatly appreciated.
Thanks again!

**Comment by kv01** [comment]
I understand that this is an unusual output and poorly explained. The format of the gylph splines was something I unfortunately only considered for a specific type of rendering technique which draws triangles and counts overlaps in a shader to compute the winding number. For that purpose, 2 triangles need to be drawn per curve to correctly count the complete region under the function. If you're just stepping through the path you would probably skip the first triangle.

The path list is updated like this:
```
if (!is_curve)
    path.add(p0, p1, glyph_center) //p0 = p1_previous_point
else {
    path.add(p0, p1, glyph_center)
    path.add(p0, control_point, p1)
}
```

This is how I'd step through the path with your code:
```c++
for (int i = 0; i < rGlyph.path_list.size(); i++) {
	const TTFFontParser::Path& p = rGlyph.path_list[i];

	const TTFFontParser::Curve& c0 = p.curves[0];
	path.MoveTo(c0.p0.x, c0.p0.y); //move to the first point

	for (int j = 0; j < p.curves.size(); j++) {
		const TTFFontParser::Curve& c = p.curves[j];
		if (c.is_curve) {
			path.QuadCurve({ c.p0.x, c.p0.y }, { c.p1.x, c.p1.y }, { c.p2.x, c.p2.y }); //where p1 is the curve control point
		}
		else {
			if (j != (p.curves.size() - 1))
				if (p.curves[j + 1].is_curve) //clunky test to skip the extra triangle for a curve
					continue;
			path.MoveTo(c.p1.x, c.p1.y); //move to the next point (p0 should be the previous point and p2 the center of the glyph)
		}
	}
}
```

Let me know if this gives you the result you expect. I will also add a way to output a more standard format for the path spline.

**Comment by AlexVestin** [comment]
That worked out well! I had to use a LineTo instead of MoveTo in the else statement but that's probably some issue with the path renderer I'm using. Thanks!

![Screenshot_2021-09-02_21-19-24](https://user-images.githubusercontent.com/31164322/131903705-c33121d8-c3f1-46ca-9e5c-e1575006ce49.png)
